export const formalities = [
    'Cédula de identidad',
    'Como obtener Clave Unica',
    'Acuerdo Unión Civil',
    'Nacimiento',
    'Matrimonio Civil',
    'Banco de datos personales',
    'Antecedentes penales y Registro de violencia intrafamiliar',
    'Apostilla',
    'Atención en terreno',
    'Bloqueos',
    'Convenios',
    'Defunción',
    'Discapacidad',
    'Inscripción al Registro de No Donantes',
    'Inscripción al Registro de Profesionales',
    'Inscripción al Registro de Personas Jurídicas sin fines de lucro',
    'Pasaporte y documentos de viaje',
    'Posesiones efectivas',
    'Precios',
    'Registro de Prendas sin Desplazamiento',
    'Vehículos, multas y conductores',
    'Rectifica Partida Nacimiento, Ley N°21.120 Identidad Género',
] 